FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

# Copiar los archivos .csproj directo (porque ya estamos parados en SistemaTorneo)
COPY TorneosFutbol.API/TorneosFutbol.API.csproj ./TorneosFutbol.API/
COPY TorneosFutbol.Infrastructure/TorneosFutbol.Infrastructure.csproj ./TorneosFutbol.Infrastructure/
COPY TorneosFutbol.Domain/TorneosFutbol.Domain.csproj ./TorneosFutbol.Domain/
RUN dotnet restore ./TorneosFutbol.API/TorneosFutbol.API.csproj

# Copiar todo el resto del código
COPY . ./
RUN dotnet publish ./TorneosFutbol.API/TorneosFutbol.API.csproj -c Release -o /app/out

# Etapa final: levantar la aplicación
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS final
WORKDIR /app
COPY --from=build /app/out .
EXPOSE 80
ENTRYPOINT ["dotnet", "TorneosFutbol.API.dll"]