// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TorneosFutbol.Infrastructure.Data;

#nullable disable

namespace TorneosFutbol.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260529192412_AgregarGrupoAEquipos")]
    partial class AgregarGrupoAEquipos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TorneosFutbol.Domain.Entities.Equipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("Equipos", (string)null);
                });

            modelBuilder.Entity("TorneosFutbol.Domain.Entities.Fecha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Fechas", (string)null);
                });

            modelBuilder.Entity("TorneosFutbol.Domain.Entities.Partido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FechaId")
                        .HasColumnType("uuid")
                        .HasColumnName("fecha_id");

                    b.Property<bool>("Finalizado")
                        .HasColumnType("boolean")
                        .HasColumnName("finalizado");

                    b.Property<int?>("GolesLocalReal")
                        .HasColumnType("integer")
                        .HasColumnName("goles_local_real");

                    b.Property<int?>("GolesVisitanteReal")
                        .HasColumnType("integer")
                        .HasColumnName("goles_visitante_real");

                    b.Property<Guid>("LocalId")
                        .HasColumnType("uuid")
                        .HasColumnName("local_id");

                    b.Property<Guid>("VisitanteId")
                        .HasColumnType("uuid")
                        .HasColumnName("visitante_id");

                    b.HasKey("Id");

                    b.ToTable("partidos", (string)null);
                });

            modelBuilder.Entity("TorneosFutbol.Domain.Entities.Prediccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<int>("GolesLocalPrediccion")
                        .HasColumnType("integer")
                        .HasColumnName("GolesLocalPrediccion");

                    b.Property<int>("GolesVisitantePrediccion")
                        .HasColumnType("integer")
                        .HasColumnName("GolesVisitantePrediccion");

                    b.Property<Guid>("PartidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("PartidoId");

                    b.Property<int>("PuntosGanados")
                        .HasColumnType("integer")
                        .HasColumnName("PuntosGanados");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id");

                    b.ToTable("Predicciones", (string)null);
                });

            modelBuilder.Entity("TorneosFutbol.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
