// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TorneosFutbol.Infrastructure.Data;

#nullable disable

namespace TorneosFutbol.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521002215_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TorneosFutbol.Domain.Entities.Equipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Equipos", (string)null);
                });

            modelBuilder.Entity("TorneosFutbol.Domain.Entities.Fecha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Fechas", (string)null);
                });

            modelBuilder.Entity("TorneosFutbol.Domain.Entities.Partido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FechaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Finalizado")
                        .HasColumnType("boolean");

                    b.Property<int?>("GolesLocalReal")
                        .HasColumnType("integer");

                    b.Property<int?>("GolesVisitanteReal")
                        .HasColumnType("integer");

                    b.Property<Guid>("LocalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VisitanteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Partidos", (string)null);
                });

            modelBuilder.Entity("TorneosFutbol.Domain.Entities.Prediccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("GolesLocalPrediccion")
                        .HasColumnType("integer");

                    b.Property<int>("GolesVisitantePrediccion")
                        .HasColumnType("integer");

                    b.Property<Guid>("PartidoId")
                        .HasColumnType("uuid");

                    b.Property<int>("PuntosGanados")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Predicciones", (string)null);
                });

            modelBuilder.Entity("TorneosFutbol.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
